# A versão do formato de arquivo (mantenha a 3.1)
version: "3.1"

# O idioma que o seu bot entende.
language: "pt"

#
# NLU PIPELINE (Processamento de Linguagem Natural)
# Usando o pipeline de embeddings (DIETClassifier) que é padrão e robusto.
#
pipeline:
# 1. Tokenização e Featurização
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "rasa/LaBSE" # Modelo que lida bem com Português
- name: RegexFeaturizer

# 2. Featurização de Texto (necessário para o DIET)
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

# 3. Classificador Principal
- name: DIETClassifier      # Classificador para Intentos e Entidades
  epochs: 100
  constrain_similarities: true

# 4. Outros Classificadores/Mapeadores
- name: EntitySynonymMapper
- name: ResponseSelector    # Para lidar com FAQs (Perguntas Frequentes)
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier  # Fallback de NLU
  threshold: 0.7
  ambiguity_threshold: 0.1

#
# CORE POLICIES (Gerenciamento de Diálogo)
#
policies:
- name: MemoizationPolicy
- name: RulePolicy    # Lida com regras (rules.yml)
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20250929-201649-undirected-berry
